### ISSUE TITLE
[Question] Linux: USB-Audio Card

### ISSUE THREAD

**Issue by pvitaliy84** [libcala/wavy#16]
How to choose external USB-audio card for record?

**Comment by AldaronLau** [comment]
@pvitaliy84 Currently this wavy connects to the `default` ALSA configuration.  If you're running pulseaudio you should be able to select your external audio card in `pavucontrol`, and set it as the default card (you do this by setting other audio cards to "fallback").  You can also do it in gnome-settings, if you're on gnome (which is a bit easier).  Otherwise, you'll have to mess with the ALSA config files.

Eventually (hopefully soon), I plan to add an API which you can use to build an interface to select the audio card you want to use.  I actually need this feature for a side-project, so I might try to set aside some time for it in the near future.

**Comment by AldaronLau** [comment]
You can now do (in wavy 0.6.0):

```rust
use wavy::MicrophoneId;

let microphones = MicrophoneId::query();
for (id, microphone) in microphones.iter().enumerate() {
    println!("[{}] {}", id, microphone);
}

// Prompt the user to select a microphone by ID, or hardcode it
...

let microphone = microphones[user_chosen_id].connect::<ChosenAudioFormat>().expect("Microphone unplugged");

// Record audio (same API as before)
...
```

**Comment by pvitaliy84** [comment]
Very cool! I will try it in evening.

And another question: how to stop record/play?

**Comment by AldaronLau** [comment]
If you want the microphone to stop, you can put it in an `Option` and set it to `None`.  When you want it start again you can reconnect and set the variable to `Some`.
